### PR TITLE
Add `RichExceptionChainRepr` for richer exception highlighting

### PR DESCRIPTION
**Pull request by joshuadavidthomas**
Yanked most of `__rich_console__` from Rich's `Traceback` class and adapted for pytest's `ExceptionChainRepr`.

I ignored locals for the time being, which I assume I can grab from `reprlocals` on each `ReprEntry`.

There's no testing other than the eye test and the code could stand to be cleaned up a bit as well. But! It's working.

image

### CODE REVIEW

**Comment by nicoddemus** [comment]
This looks *amazing* 😍 great work!

About testing: not sure how we can approach testing in pytest-rich in general TBH. Any ideas?

**Comment by joshuadavidthomas** [comment]
For the time being, could we use a mark on failing tests so that you could manually test the terminal output for tracebacks without breaking CI?

**Comment by nicoddemus** [comment]
> Guess my implementation of _grab_err_msg needs some updating..

Yeah I guess somewhere there's a `None` that needs to be handled as text.

**Comment by joshuadavidthomas** [comment]
First pass at dealing with the error messages.

The original `_grab_err_msg` function couldn't deal with a plain assertion without a message, e.g. `assert 0` vs `assert 0, "Some failure"`. Fixed that and moved it to within the `render_chain` method for now.

Here are a few screenshots to show progress so far:

image

image

image

**Comment by joshuadavidthomas** [comment]
From my previously mentioned Django app, it works *and* looks a lot better:

image

**Comment by joshuadavidthomas** [comment]
This PR may be in a good spot to merge. 

There are still improvments to be done:
- I'm not 100% in love with how the error messages are displayed, could explore a richer way to output them
- The code for `RichExceptionChainRepr` could probably stand to be cleaned up and refactored a bit
- Along with the refactoring, documentation in docstrings would be useful for future contributors

I think those all could go in as separate issues with their own PRs, in order to avoid this PR's scope from expanding beyond richer exception highlighting.

**Comment by joshuadavidthomas** [comment]
Additional stray thoughts:
- May want to rename the header from `Traceback` to something else (Failed Test Report?), since it's not an actual traceback it's a bit misleading for the header to say it is
- Still need to include the `reprlocals` information from the `ReprEntry` somewhere

**Comment by nicoddemus** [comment]
> This PR may be in a good spot to merge.

Agreed, want to mark it as Ready for Review then?

**Comment by joshuadavidthomas** [comment]
Final tweaks, ready for review!

image

**Comment by joshuadavidthomas** [comment]
Areas for improvement:

- pytest's `TerminalReporter` shows the entire test function being called, whereas since I adapted from rich's `Traceback`, `RichReporter` only shows the last 3 and next 3 lines from the failed line.

image

image

- `TerminalReporter` puts the error messages right after the failed lines, whereas `RichReporter` puts them at the bottom. Switching away from rich's `Syntax` object would make this easier, as `Syntax` is apparently not designed to be composed in pieces [as detailed by Will here](https://github.com/Textualize/rich/issues/1829#issuecomment-1012227064).

image

image

**Review by nicoddemus — APPROVED** [review]
This looks awesome!

I didn't review the code in detail, but the results do look great.

Could you please also update the screenshot in `assets/`? Thanks!

**Comment by nicoddemus** [comment]
Btw your detailed comments for follow ups should probably be moved to their own issues so we don't lose track of them. 👍

**Comment by joshuadavidthomas** [comment]
Added new issues on where to go from here:

#16
#17

**Comment by fruch** [comment]
When I ever thought about pytest+rich, this is the feature I had in mind.

**Pull request merged**
