### PR TITLE
Add `pytest_report_header` hook output to header panel

### LINKED ISSUE #10: Allow for other plugins to add to report header
If you use another pytest plugin that adds additional info to the report header, e.g. `pytest-django` adds a line containing information about the Django app being tested, `pytest-rich` doesn't display this.

### PR DESCRIPTION
**Pull request by joshuadavidthomas**
Closes #10

### CODE REVIEW

**Comment by joshuadavidthomas** [comment]
Once #65 lands I can update this PR with a screenshot of the change. 

Not a bad idea to require screenshots on any PRs that update any of the output to terminal.

**Review by nicoddemus — APPROVED** [review]

**Comment by joshuadavidthomas** [comment]
Or even better have a GHA that generates the file and posts it as a comment on the PR.

**Comment by joshuadavidthomas** [comment]
@nicoddemus 👀

## Screenshot

pytest_rich-20221104_212337

**Comment by joshuadavidthomas** [comment]
I have opened an issue (#72) to track the auto uploading of screenshots on PRs.

**Pull request merged**
