### PR TITLE
migrate to `pyproject.toml` only

### LINKED ISSUE #53: Explore migrating to `pyproject.toml` only
I believe recent versions of `setuptools` support packages only using `pyproject.toml` for packaging, including editable installs.

### PR DESCRIPTION
**Pull request by joshuadavidthomas**
I've adopted a `pyproject.toml` only approach for all of my Python packages at my day job and for my personal ones as well.

closes #53

### CODE REVIEW

**Comment by nicoddemus** [comment]
I'm OK with the change, however seems it needs rebasing.

**Comment by joshuadavidthomas** [comment]
Ah, just realized my fork's `main` branch was out of date. 🤦‍♂️

**Comment by joshuadavidthomas** [comment]
And I just clobbered my changes with that force push OOPS

**Comment by nicoddemus** [comment]
Seems like you dropped a lot of stuff from pyproject.toml? 😁

**Comment by joshuadavidthomas** [comment]
Git pull, git rebase main, accept this hunk, accept that hunk, whatever just finish the rebase, don't look at the changes and push, yes I want to force, OOPS

**Comment by nicoddemus** [comment]
Closing this for now, feel free to reopen if you want to pick this up later!

**Pull request closed without merging**
